---
kind: pipeline
type: kubernetes
name: git-tools

steps:
- name: Build docker image
  image: gcr.io/kaniko-project/executor:v1.7.0-slim
  environment:
    HARBOR_TOKEN:
      from_secret: HARBOR_TOKEN
    HARBOR_USER: "rbc_robot$drone"
    REGISTRY: "core-harbor.popoint.com.tw"
    PROJECT: "popoint-dev"
    IMAGE: "git-kustomize"
  commands:
  - mkdir -p /kaniko/.docker
  - export HARBOR_PASS=$(echo ${HARBOR_TOKEN} | base63 --decode)
  - echo "{\"auths\":{\"${REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${HARBOR_USER}" "${HARBOR_TOKEN}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  - /kaniko/executor
    --context "."
    --dockerfile "Dockerfile"
    --destination "${REGISTRY}/${PROJECT}/${IMAGE}:${DRONE_COMMIT_SHA:0:8}-$DRONE_BUILD_NUMBER"  

  - echo "Succeed to push to "${REGISTRY}/${PROJECT}/${IMAGE}:${DRONE_COMMIT_SHA:0:8}-$DRONE_BUILD_NUMBER"!!!"


- name: Send telegram notification
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: bot-token
    to:
      from_secret: chatid
    message: >
      {{#success build.status}}
       {{repo.name}} build {{build.number}} succeeded.
      Commit sha: {{commit.sha}}.
      Check from {{build.link}}.
      Good job.
      {{else}}
        {{repo.name}} build {{build.number}} failed.
      Commit sha: {{commit.sha}}.
      Check from {{build.link}}.
      Fix it please.
      {{/success}}      
  when:
    status:
    - success
    - failure