---
kind: pipeline
type: kubernetes
name: git-tools

steps:


- name: Build and Push docker image
  image: core-harbor.popoint.com.tw/library/drone-kaniko:v0.6
  environment:
    TAG: v0.1-${DRONE_COMMIT_SHA:0:8}-${DRONE_BUILD_NUMBER}
    BASE64_TOKEN:
      from_secret: HARBOR_RD_TOKENBASE64
    REGISTRY_USER: "rbc_robot$drone"
    DOCKERFILE_PATH: "Dockerfile"
    REGISTRY: "core-harbor.popoint.com.tw"
    PROJECT_ID: "library"
    IMAGE_PATH: "git-kustomize"
  commands:
  - /drone-kaniko/entrypoint.sh
  - cat /kaniko/.docker/config.json
  - /drone-kaniko/executor --dockerfile=$DOCKERFILE_PATH \
    --context=$KANIKO_CRED \
    --destination "$REGISTRY/$PROJECT_ID/$IMAGE_PATH:$TAG" \
    --context dir:/./

- name: Send telegram notification
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: bot-token
    to:
      from_secret: chatid
    message: >
      {{#success build.status}}
       {{repo.name}} build {{build.number}} succeeded.
      Commit sha: {{commit.sha}}.
      Check from {{build.link}}.
      Good job.
      {{else}}
        {{repo.name}} build {{build.number}} failed.
      Commit sha: {{commit.sha}}.
      Check from {{build.link}}.
      Fix it please.
      {{/success}}      
  when:
    status:
    - success
    - failure

volumes:
- name: cred
  temp: {}